name: eddy-footprint
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Required dependencies
  - python>=3.9
  - cartopy
  - gdal
  - jupyter
  - matplotlib
  - mpmath
  - numpy
  - pre-commit
  - pytest
  - pytest-cov
  - rasterio
  - rioxarray
  - scipy
  - xarray
