name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main
    paths-ignore:
      - ".github/workflows/*-release.yaml"
      - "doc/**"
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    name: ${{ matrix.python-version }}-build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Create conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          micromamba-version: "latest"
          environment-file: ci/environment.yml
          extra-specs: |
            python=${{ matrix.python-version }}

      - name: Conda info
        run: conda info

      - name: Install eddy-footprint
        run: |
          python -m pip install -e . --no-deps

      - name: Conda list
        run: conda list

      - name: Running Tests
        run: |
          python -m pytest --cov=./ --cov-report=xml --verbose

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
